fix(ci): stop using hardcoded dependency versions
Use the versions defined in the pyproject.toml file

diff --git a/.github/workflows/bump_version_and_tag.yml b/.github/workflows/bump_version_and_tag.yml
--- a/.github/workflows/bump_version_and_tag.yml
+++ b/.github/workflows/bump_version_and_tag.yml
@@ -40,8 +40,25 @@ jobs:
 
       - name: Install dependencies
         run: |
-          python -m pip install 'pip==25.0.1'
-          pip install 'packaging==24.0'
+          export PIP_VERSION=$(grep -oP 'pip\s*==\s*\K([0-9]+\.[0-9]+\.[0-9]+)' pyproject.toml || echo '')
+          if [ -z "$PIP_VERSION" ]; then
+            echo '::warning title=Could not detect pip version::in pyproject.toml; falling back to latest.'
+            PIP_INSTALL="pip"
+          else
+            echo "Will install pip version $PIP_VERSION."
+            PIP_INSTALL="pip==$PIP_VERSION"
+          fi
+          python -m pip install "$PIP_INSTALL"
+
+          export PACKAGING_VERSION=$(grep -oP 'packaging\s*==\s*\K([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)' pyproject.toml || echo '')
+          if [ -z "$PACKAGING_VERSION" ]; then
+            echo '::warning title=Could not detect packaging version::in pyproject.toml; falling back to latest.'
+            PACKAGING_INSTALL="packaging"
+          else
+            echo "Will install packaging version $PACKAGING_VERSION."
+            PACKAGING_INSTALL="packaging==$PACKAGING_VERSION"
+          fi
+          pip install "$PACKAGING_INSTALL"
 
       - name: Validate version format
         run: |
