fix(ruff): use the version defined in the pyproject.toml file
Avoids code duplication

diff --git a/.github/workflows/ruff.yml b/.github/workflows/ruff.yml
--- a/.github/workflows/ruff.yml
+++ b/.github/workflows/ruff.yml
@@ -35,7 +35,14 @@ jobs:
       # Ruff does not need a specific python version installed
       - name: Install dependencies
         run: |
-          python -m pip install 'ruff==0.11.13'
+          export RUFF_VERSION=$(grep -oP "^ruff\s*==\s*\K([0-9]+\.[0-9]+\.[0-9]+)" pyproject.toml || echo '')
+          if [ -z "$RUFF_VERSION" ]; then
+            echo "Could not detect Ruff version in pyproject.toml; falling back to latest."
+            python -m pip install ruff
+          else
+            echo "Will install ruff version $RUFF_VERSION."
+            python -m pip install "ruff==$RUFF_VERSION"
+          fi
 
       - name: Lint with Ruff
         run: |
